version: "3"

services:
  #
  # Rested Kafka
  #
  rested-kafka:
    image: go-kafka-consumer:0.1.0
    ports:
      - "8099:8080"
    environment:
      - KAFKA_BROKER_URLS=kafka:9092
      - KAFKA_TOPIC=testing-topic
      - KAFKA_GROUP_ID=group-id
  #
  # Kafka
  #
  kafka:
    container_name: kafka
    image: lensesio/fast-data-dev
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "3030:3030"
    environment:
      - ADV_HOST=kafka
      - ADV_PORT=9092
      - SAMPLEDATA=0
